---
# tasks file for motd

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"


- include: CentOS.yml
  when: ansible_distribution == "CentOS"


- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"


- name: Create motd file
  become: yes
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

