---
galaxy_info:
  author: xxxx
  description: Generates MOTD file.
  company: LAB
  license: BSD
  min_ansible_version: 1.9
  github_branch: master
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
  - system
dependencies: []
