- name: Print some debug information 
  vars: 
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info

#run info
#ansible-playbook --tags "debug_info" -i hosts/mvps.host HostOS.yml
