---
- hosts: all
  vars:
    myvar: "{{ ansible_facts.eth0.ipv4.address }}"
  tasks:
    - debug:
        msg: "my var is {{ ansible_facts.eth0.ipv4.address }}"
      when: ansible_facts.eth0.ipv4.address is defined
    - debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_facts.eth0.ipv4.address is defined
    - debug:
        msg: "Host inventory {{ inventory_hostname }}"

